export const quickCommands = [
	{
		category: "System",
		commands: [
			{ name: "Shutdown", icon: "⚡", command: "shutdown /s /t 0", description: "Shutdown PC immediately" },
			{ name: "Restart", icon: "🔄", command: "shutdown /r /t 0", description: "Restart PC immediately" },
			{ name: "Sleep", icon: "😴", command: "rundll32.exe powrprof.dll,SetSuspendState 0,1,0", description: "Put PC to sleep" },
			{ name: "Lock", icon: "🔒", command: "rundll32.exe user32.dll,LockWorkStation", description: "Lock workstation" },
			{ name: "Hibernate", icon: "💤", command: "shutdown /h", description: "Hibernate PC" },
			{ name: "Log Off", icon: "👋", command: "shutdown /l", description: "Log off current user" },
		],
	},
	{
		category: "Applications",
		commands: [
			{ name: "Notepad", icon: "📝", command: "start notepad", description: "Open Notepad" },
			{ name: "Calculator", icon: "🔢", command: "start calc", description: "Open Calculator" },
			{ name: "Task Manager", icon: "📊", command: "start taskmgr", description: "Open Task Manager" },
			{ name: "Command Prompt", icon: "⌨️", command: "start cmd", description: "Open CMD" },
			{ name: "PowerShell", icon: "💻", command: "start powershell", description: "Open PowerShell" },
			{ name: "Paint", icon: "🎨", command: "start mspaint", description: "Open Paint" },
			{ name: "File Explorer", icon: "📁", command: "start explorer", description: "Open File Explorer" },
			{ name: "Control Panel", icon: "⚙️", command: "start control", description: "Open Control Panel" },
			{ name: "Settings", icon: "🔧", command: "start ms-settings:", description: "Open Windows Settings" },
			{ name: "Registry Editor", icon: "📋", command: "start regedit", description: "Open Registry Editor" },
		],
	},
	{
		category: "System Info",
		commands: [
			{ name: "System Info", icon: "💻", command: "systeminfo", description: "Display system information" },
			{ name: "IP Config", icon: "🌐", command: "ipconfig /all", description: "Display network configuration" },
			{ name: "Task List", icon: "📋", command: "tasklist", description: "List running processes" },
			{ name: "Disk Info", icon: "💾", command: "wmic logicaldisk get name,size,freespace", description: "Show disk space" },
			{ name: "Battery Status", icon: "🔋", command: "WMIC Path Win32_Battery Get EstimatedChargeRemaining", description: "Check battery level" },
			{ name: "CPU Info", icon: "🖥️", command: "wmic cpu get name,maxclockspeed,numberofcores", description: "Display CPU details" },
			{ name: "RAM Info", icon: "🧠", command: "wmic memorychip get capacity,speed", description: "Display RAM details" },
			{ name: "OS Version", icon: "🪟", command: "ver", description: "Show Windows version" },
		],
	},
	{
		category: "Network",
		commands: [
			{ name: "Ping Google", icon: "📡", command: "ping google.com -n 4", description: "Test internet connection" },
			{ name: "Network Stats", icon: "📈", command: "netstat -an", description: "Show network statistics" },
			{ name: "DNS Flush", icon: "🔄", command: "ipconfig /flushdns", description: "Clear DNS cache" },
			{ name: "Trace Route", icon: "🗺️", command: "tracert google.com", description: "Trace route to Google" },
			{ name: "WiFi Passwords", icon: "🔑", command: "netsh wlan show profiles", description: "Show saved WiFi networks" },
			{ name: "Active Connections", icon: "🔗", command: "netstat -ano", description: "Show active connections" },
			{ name: "Network Adapters", icon: "📶", command: "ipconfig /all", description: "List network adapters" },
		],
	},
	{
		category: "Files & Folders",
		commands: [
			{ name: "List Desktop", icon: "🖥️", command: "dir %USERPROFILE%\\Desktop", description: "List desktop files" },
			{ name: "List Downloads", icon: "⬇️", command: "dir %USERPROFILE%\\Downloads", description: "List downloads" },
			{ name: "List Documents", icon: "📄", command: "dir %USERPROFILE%\\Documents", description: "List documents" },
			{ name: "Open Desktop", icon: "📂", command: "start %USERPROFILE%\\Desktop", description: "Open Desktop folder" },
			{ name: "Open Downloads", icon: "📥", command: "start %USERPROFILE%\\Downloads", description: "Open Downloads folder" },
			{ name: "Temp Files", icon: "🗑️", command: "dir %TEMP%", description: "List temp files" },
			{ name: "Recent Files", icon: "🕐", command: "dir %APPDATA%\\Microsoft\\Windows\\Recent", description: "Show recent files" },
		],
	},
	{
		category: "Process Management",
		commands: [
			{ name: "Kill Chrome", icon: "🔴", command: "taskkill /F /IM chrome.exe", description: "Force close Chrome" },
			{ name: "Kill Edge", icon: "🔴", command: "taskkill /F /IM msedge.exe", description: "Force close Edge" },
			{ name: "Kill Firefox", icon: "🔴", command: "taskkill /F /IM firefox.exe", description: "Force close Firefox" },
			{ name: "Kill Notepad", icon: "🔴", command: "taskkill /F /IM notepad.exe", description: "Force close Notepad" },
			{ name: "Process Tree", icon: "🌳", command: "tasklist /V", description: "Show detailed process list" },
		],
	},
	{
		category: "Disk & Cleanup",
		commands: [
			{ name: "Disk Cleanup", icon: "🧹", command: "cleanmgr", description: "Open Disk Cleanup" },
			{ name: "Check Disk", icon: "🔍", command: "chkdsk C:", description: "Check C: drive for errors" },
			{ name: "Defragment", icon: "📊", command: "defrag C: /U /V", description: "Defragment C: drive" },
			{ name: "Clear Temp", icon: "🗑️", command: "del /q/f/s %TEMP%\\*", description: "Delete temp files" },
			{ name: "Empty Recycle", icon: "♻️", command: "rd /s /q %systemdrive%\\$Recycle.bin", description: "Empty recycle bin" },
			{ name: "Disk Usage", icon: "💿", command: "wmic logicaldisk get size,freespace,caption", description: "Show disk usage" },
		],
	},
	{
		category: "Security & Privacy",
		commands: [
			{ name: "Firewall Status", icon: "🛡️", command: "netsh advfirewall show allprofiles", description: "Check firewall status" },
			{ name: "Windows Defender", icon: "🔰", command: "start windowsdefender:", description: "Open Windows Defender" },
			{ name: "Clear History", icon: "🧼", command: "RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 255", description: "Clear browser history" },
			{ name: "Event Viewer", icon: "📜", command: "start eventvwr", description: "Open Event Viewer" },
			{ name: "User Accounts", icon: "👥", command: "net user", description: "List user accounts" },
			{ name: "Security Center", icon: "🔐", command: "start wscui.cpl", description: "Open Security Center" },
		],
	},
	{
		category: "Performance",
		commands: [
			{ name: "Resource Monitor", icon: "📊", command: "start perfmon /res", description: "Open Resource Monitor" },
			{ name: "Performance Monitor", icon: "📈", command: "start perfmon", description: "Open Performance Monitor" },
			{ name: "Memory Usage", icon: "🧠", command: "wmic OS get FreePhysicalMemory,TotalVisibleMemorySize", description: "Check RAM usage" },
			{ name: "CPU Usage", icon: "⚙️", command: "wmic cpu get loadpercentage", description: "Check CPU usage" },
			{ name: "Startup Programs", icon: "🚀", command: "wmic startup get caption,command", description: "List startup programs" },
			{ name: "Services", icon: "🔧", command: "start services.msc", description: "Open Services" },
		],
	},
	{
		category: "Advanced",
		commands: [
			{ name: "Device Manager", icon: "🔌", command: "start devmgmt.msc", description: "Open Device Manager" },
			{ name: "Disk Management", icon: "💽", command: "start diskmgmt.msc", description: "Open Disk Management" },
			{ name: "Computer Management", icon: "🖥️", command: "start compmgmt.msc", description: "Open Computer Management" },
			{ name: "Group Policy", icon: "📋", command: "start gpedit.msc", description: "Open Group Policy Editor" },
			{ name: "System Properties", icon: "⚙️", command: "start sysdm.cpl", description: "Open System Properties" },
			{ name: "Environment Vars", icon: "🌍", command: "rundll32 sysdm.cpl,EditEnvironmentVariables", description: "Edit environment variables" },
			{ name: "Scheduled Tasks", icon: "⏰", command: "start taskschd.msc", description: "Open Task Scheduler" },
			{ name: "System Restore", icon: "⏮️", command: "rstrui.exe", description: "Open System Restore" },
		],
	},
	{
		category: "Utilities",
		commands: [
			{ name: "Screenshot", icon: "📸", command: "start snippingtool", description: "Open Snipping Tool" },
			{ name: "Character Map", icon: "🔤", command: "start charmap", description: "Open Character Map" },
			{ name: "Magnifier", icon: "🔍", command: "start magnify", description: "Open Magnifier" },
			{ name: "On-Screen Keyboard", icon: "⌨️", command: "start osk", description: "Open On-Screen Keyboard" },
			{ name: "Sound Settings", icon: "🔊", command: "start mmsys.cpl", description: "Open Sound Settings" },
			{ name: "Display Settings", icon: "🖥️", command: "start desk.cpl", description: "Open Display Settings" },
			{ name: "Date & Time", icon: "🕐", command: "start timedate.cpl", description: "Open Date & Time Settings" },
			{ name: "Mouse Settings", icon: "🖱️", command: "start main.cpl", description: "Open Mouse Settings" },
		],
	},
];
